export const HTTP_METHODS = ['GET','POST','PUT','PATCH','DELETE'] as const
export const STATUS_CODE = { OK:200, CREATED:201, BAD_REQUEST:400, UNAUTHORIZED:401, FORBIDDEN:403, NOT_FOUND:404, SERVER_ERROR:500 } as const
export const RATE_LIMIT = { WINDOW_MS:60_000, MAX:60 } as const
