export const STATUS = { PENDING:'PENDING', RUNNING:'RUNNING', COMPLETED:'COMPLETED', FAILED:'FAILED' } as const
export const EV = { STARTED:'EXECUTION_STARTED', COMPLETED:'EXECUTION_COMPLETED', FAILED:'EXECUTION_FAILED', NODE_START:'NODE_STARTED', NODE_DONE:'NODE_COMPLETED', NODE_FAIL:'NODE_FAILED', LOG:'LOG' } as const
